# Inventory generado automáticamente
# Red escaneada: 10.252.25.0/24
# Archivo fuente: macs_thinkpad.txt

[devices]
thinkpad81 ansible_host=10.185.97.255 mac_address=00:41:0E:DC:BE:0B host_name=thinkpad81 estado=no_encontrado
thinkpad82 ansible_host=10.185.97.255 mac_address=00:41:0E:DC:C5:C5 host_name=thinkpad82 estado=no_encontrado
thinkpad83 ansible_host=10.185.97.255 mac_address=00:41:0E:FD:CB:9B host_name=thinkpad83 estado=no_encontrado
thinkpad84 ansible_host=10.185.97.255 mac_address=00:41:0E:FD:DC:A3 host_name=thinkpad84 estado=no_encontrado
thinkpad85 ansible_host=10.185.97.184 mac_address=00:41:0E:FD:DC:FD host_name=thinkpad85 estado=no_encontrado
thinkpad86 ansible_host=10.185.97.149 mac_address=00:41:0E:FD:81:FD host_name=thinkpad86 estado=no_encontrado
thinkpad87 ansible_host=10.185.97.155 mac_address=00:41:0E:FD:82:4B host_name=thinkpad87 estado=no_encontrado
thinkpad88 ansible_host=10.252.25.35 mac_address=00:41:0E:FD:CB:69 host_name=thinkpad88
thinkpad89 ansible_host=10.252.25.189 mac_address=00:41:0E:FD:C9:F7 host_name=thinkpad89
thinkpad90 ansible_host=10.252.25.93 mac_address=00:41:0E:FD:DC:B5 host_name=thinkpad90
thinkpad91 ansible_host=10.252.25.119 mac_address=00:41:0E:FD:82:1B host_name=thinkpad91
thinkpad92 ansible_host=10.252.25.133 mac_address=00:41:0E:FD:D4:85 host_name=thinkpad92
thinkpad93 ansible_host=10.185.97.207 mac_address=00:41:0E:FD:D5:1D host_name=thinkpad93 estado=no_encontrado

[devices:vars]
ansible_user=me.millan
ansible_become=yes
ansible_connection=ssh
