# Inventory generado automáticamente
# Red escaneada: 172.28.222.0/24
# Archivo fuente: macs_1fpb_alu.txt

[devices]
fpb105 ansible_host=172.28.222.72 mac_address=B0:6E:BF:82:7A:B0 host_name=fpb105
fpb103 ansible_host=172.28.222.88 mac_address=B0:6E:BF:82:7A:2D host_name=fpb103
fpb107 ansible_host=172.28.222.35 mac_address=B0:6E:BF:CC:6B:27 host_name=fpb107
fpb106 ansible_host=172.28.222.50 mac_address=B0:6E:BF:CC:6B:38 host_name=fpb106
fpb104 ansible_host=172.28.222.56 mac_address=B0:6E:BF:CC:68:95 host_name=fpb104
fpb101 ansible_host=172.28.222.64 mac_address=B4:2E:99:BD:9F:4B host_name=fpb101
fpb102 ansible_host=172.28.222.214 mac_address=B0:6E:BF:CC:6C:67 host_name=fpb102

[devices:vars]
ansible_user=me.millan
ansible_become=yes
ansible_connection=ssh
